import type { Customer, Invoice, Payment, Profile } from "./types";

export const DEFAULT_PROFILE: Profile = {
  fullName: "Alex Morgan",
  email: "alex@example.com",
  businessName: "Morgan Studio",
  businessAddress: "24 Harbor Street, Lisbon, Portugal",
  invoicePrefix: "INV",
  paymentTerms: "Net 14",
  defaultCurrency: "USDC",
  acceptedCurrencies: ["USDC", "SOL"],
};

export const MERCHANT_WALLET = "8h3Kq7vTn4pRyLwBcXz1AeD6sMf5Gk92Lm";
export const DEMO_WALLET = "7xKq3nVfPzD8sYtLbRcW1uHg5AeM4Jd92Lm";

export const MOCK_INVOICES: Invoice[] = [
  {
    id: "inv-124",
    number: "INV-00124",
    clientName: "Acme Design",
    clientEmail: "billing@acmedesign.com",
    description: "Website Development",
    items: [{ id: "i1", description: "Website Development", quantity: 1, rate: 500 }],
    currency: "USDC",
    issueDate: "2026-08-28",
    dueDate: "2026-09-10",
    createdAt: "2026-08-28",
    status: "paid",
    notes: "Thank you for your business.",
    txSignature: "5K8xQvT7nRpLyMbWcZ1aD6sGf4Jk2eH9F92",
    paidAt: "2026-08-28",
  },
  {
    id: "inv-123",
    number: "INV-00123",
    clientName: "Sarah Johnson",
    clientEmail: "sarah@johnson.co",
    description: "Brand Identity Package",
    items: [{ id: "i1", description: "Brand Identity Package", quantity: 1, rate: 850 }],
    currency: "USDC",
    issueDate: "2026-08-27",
    dueDate: "2026-09-09",
    createdAt: "2026-08-27",
    status: "pending",
    notes: "Thank you for your business.",
  },
  {
    id: "inv-122",
    number: "INV-00122",
    clientName: "TechHub",
    clientEmail: "accounts@techhub.io",
    description: "Platform Consulting — August",
    items: [{ id: "i1", description: "Consulting hours", quantity: 8, rate: 150 }],
    currency: "USDC",
    issueDate: "2026-08-25",
    dueDate: "2026-09-05",
    createdAt: "2026-08-25",
    status: "paid",
    txSignature: "3Ap9RvL2nQxTyKbMcZ7aD1sGf8Jk4eH5B21",
    paidAt: "2026-08-26",
  },
  {
    id: "inv-121",
    number: "INV-00121",
    clientName: "David Smith",
    clientEmail: "david@smithlabs.dev",
    description: "Landing Page Revamp",
    items: [{ id: "i1", description: "Landing Page Revamp", quantity: 1, rate: 300 }],
    currency: "USDC",
    issueDate: "2026-08-24",
    dueDate: "2026-08-26",
    createdAt: "2026-08-24",
    status: "overdue",
  },
  {
    id: "inv-120",
    number: "INV-00120",
    clientName: "Northwind Media",
    clientEmail: "pay@northwind.media",
    description: "Motion graphics pack",
    items: [{ id: "i1", description: "Motion graphics pack", quantity: 2, rate: 400 }],
    currency: "SOL",
    issueDate: "2026-08-19",
    dueDate: "2026-09-02",
    createdAt: "2026-08-19",
    status: "paid",
    txSignature: "9Fq4RvL8nZxTyKbMcP7aD1sGf2Jk6eH3C77",
    paidAt: "2026-08-21",
  },
  {
    id: "inv-119",
    number: "INV-00119",
    clientName: "Lumen Labs",
    clientEmail: "finance@lumenlabs.ai",
    description: "API integration retainer",
    items: [{ id: "i1", description: "API integration retainer", quantity: 1, rate: 1300 }],
    currency: "USDC",
    issueDate: "2026-08-15",
    dueDate: "2026-08-29",
    createdAt: "2026-08-15",
    status: "draft",
  },
];

export const MOCK_CUSTOMERS: Customer[] = [
  { id: "c1", name: "Acme Design", email: "billing@acmedesign.com", invoices: 6, totalBilled: 3200 },
  { id: "c2", name: "TechHub", email: "accounts@techhub.io", invoices: 4, totalBilled: 4800 },
  { id: "c3", name: "Sarah Johnson", email: "sarah@johnson.co", invoices: 3, totalBilled: 1950 },
  { id: "c4", name: "Northwind Media", email: "pay@northwind.media", invoices: 2, totalBilled: 1600 },
  { id: "c5", name: "David Smith", email: "david@smithlabs.dev", invoices: 2, totalBilled: 600 },
];

export const MOCK_PAYMENTS: Payment[] = [
  {
    id: "p1",
    invoiceNumber: "INV-00124",
    clientName: "Acme Design",
    amount: 500,
    currency: "USDC",
    date: "2026-08-28",
    txSignature: "5K8xQvT7nRpLyMbWcZ1aD6sGf4Jk2eH9F92",
  },
  {
    id: "p2",
    invoiceNumber: "INV-00122",
    clientName: "TechHub",
    amount: 1200,
    currency: "USDC",
    date: "2026-08-26",
    txSignature: "3Ap9RvL2nQxTyKbMcZ7aD1sGf8Jk4eH5B21",
  },
  {
    id: "p3",
    invoiceNumber: "INV-00120",
    clientName: "Northwind Media",
    amount: 800,
    currency: "SOL",
    date: "2026-08-21",
    txSignature: "9Fq4RvL8nZxTyKbMcP7aD1sGf2Jk6eH3C77",
  },
];

export const REVENUE_SERIES = [
  { day: "Jul 30", amount: 120 },
  { day: "Aug 2", amount: 340 },
  { day: "Aug 5", amount: 260 },
  { day: "Aug 8", amount: 520 },
  { day: "Aug 11", amount: 410 },
  { day: "Aug 14", amount: 780 },
  { day: "Aug 17", amount: 640 },
  { day: "Aug 20", amount: 980 },
  { day: "Aug 23", amount: 860 },
  { day: "Aug 26", amount: 1200 },
  { day: "Aug 28", amount: 1420 },
];
