/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as InvoicesIndexRouteImport } from './routes/invoices/index'
import { Route as InvoicesInvoiceIdRouteImport } from './routes/invoices/$invoiceId'
import { Route as InvoicesNewRouteImport } from './routes/invoices/new'
import { Route as PayInvoiceIdRouteImport } from './routes/pay/$invoiceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesInvoiceIdRoute = InvoicesInvoiceIdRouteImport.update({
  id: '/invoices/$invoiceId',
  path: '/invoices/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesNewRoute = InvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PayInvoiceIdRoute = PayInvoiceIdRouteImport.update({
  id: '/pay/$invoiceId',
  path: '/pay/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/pay/$invoiceId': typeof PayInvoiceIdRoute
  '/invoices/': typeof InvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/pay/$invoiceId': typeof PayInvoiceIdRoute
  '/invoices': typeof InvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/pay/$invoiceId': typeof PayInvoiceIdRoute
  '/invoices/': typeof InvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/signin'
    | '/signup'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/pay/$invoiceId'
    | '/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/signin'
    | '/signup'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/pay/$invoiceId'
    | '/invoices'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/signin'
    | '/signup'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/pay/$invoiceId'
    | '/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  InvoicesInvoiceIdRoute: typeof InvoicesInvoiceIdRoute
  InvoicesNewRoute: typeof InvoicesNewRoute
  PayInvoiceIdRoute: typeof PayInvoiceIdRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$invoiceId': {
      id: '/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof InvoicesInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/new': {
      id: '/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof InvoicesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$invoiceId': {
      id: '/pay/$invoiceId'
      path: '/pay/$invoiceId'
      fullPath: '/pay/$invoiceId'
      preLoaderRoute: typeof PayInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  InvoicesInvoiceIdRoute: InvoicesInvoiceIdRoute,
  InvoicesNewRoute: InvoicesNewRoute,
  PayInvoiceIdRoute: PayInvoiceIdRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
